### ISSUE TITLE
flyout form filters not working in 1.10

### ISSUE THREAD

**Issue by mlzummo** [hpcc-systems/Visualization#1487]
Uncaught TypeError: vizCellMap[viz.id].widget(...).buttonAnnotations is not a function in HTML.js

http://rawgit.com/hpcc-systems/Visualization/b1.10.0-rc8/demos/marshaller/index.html?Hostname=10.173.147.1&Port=8010&Protocol=http&Wuid=W20151102-091253&ResultName=leeddx_issue_986_formddl_Comp_Ins002_DDL&HTML

vs

http://rawgit.com/hpcc-systems/Visualization/b1.8.4/demos/marshaller/index.html?Hostname=10.173.147.1&Port=8010&Protocol=http&Wuid=W20151102-091253&ResultName=leeddx_issue_986_formddl_Comp_Ins002_DDL&HTML

**Comment by GordonSmith** [comment]
Surface has annotations and MegaChart has a toolbar - you will need to check if its a MegaChart and add the button to the toolbar in that scenario.
